apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      protocol: TCP
      targetPort : 27017
  externalIPs: 
    - 192.168.44.11
  selector:
    name: mongodb-kubernetes-operator