apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
data:
  mosquitto.conf: |
    # Config file for mosquitto
    #
    # See mosquitto.conf(5) for more information.
    
    # =================================================================
    # General configuration
    # =================================================================
    
    # =================================================================
    # Default listener
    # =================================================================
    
    listener 1883 0.0.0.0

    {{- if .Values.configuration.authentication.enabled}}
    allow_anonymous false
    {{- else }}
    allow_anonymous true
    {{- end }}

    # =================================================================
    # Extra listeners
    # =================================================================
    
    {{- if .Values.configuration.ssl.enabled }}
    listener 8883 0.0.0.0

    {{- if .Values.configuration.authentication.enabled}}
    allow_anonymous false
    {{- else }}
    allow_anonymous true
    {{- end }}

    certfile {{ printf "%s%s" .Values.configuration.ssl.certfile.path ( .Values.configuration.ssl.certfile.file | default "default.pem") }}
    keyfile {{ printf "%s%s" .Values.configuration.ssl.keyfile.path ( .Values.configuration.ssl.keyfile.file | default "default.key") }}

    {{- end }}


    # =================================================================
    # Logging
    # =================================================================

    log_dest topic
    log_dest stdout
    log_type all
    log_timestamp true
    
    # -----------------------------------------------------------------
    # Default authentication and topic access control
    # -----------------------------------------------------------------
    
    {{- if .Values.configuration.authentication.enabled }}
    password_file {{ printf "%s%s" (.Values.configuration.authentication.path | default "/mosquitto/auth") "/passwd" }}
    {{- else }}
    # password_file
    {{- end }}