{{- if and .Values.configuration.ssl.enabled .Values.configuration.ssl.certfile.data }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mosquitto-certfile
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
stringData:
  default.pem: "{{ .Values.configuration.ssl.certfile.data }}"

{{- end -}}