{{- if and .Values.grafana.enabled .Values.influxdb2.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-influxdb2-grafana-datasource"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "{{ .Values.grafana.sidecar.datasources.label }}": ""
data:
  datasources.yaml: |+
    apiVersion: 1
    datasources:
      - name: opentwins
        type: influxdb
        access: proxy
        url: http://{{ include "opentwins.influxdb2.fullname" . }}:80
        isDefault: true
        jsonData:
          version: Flux
          organization: "{{ .Values.influxdb2.adminUser.organization }}"
          defaultBucket: "{{ .Values.influxdb2.adminUser.bucket }}"
          tlsSkipVerify: true
        secureJsonData:
          token: "{{ .Values.influxdb2.adminUser.token }}"

{{- end }}