apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opentwinsv2.fullname" . }}-things
  labels:
    {{- include "opentwinsv2.labels" . | nindent 4 }}
    app.kubernetes.io/component: things
spec:
  replicas: {{ .Values.opentwinsv2.things.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "opentwinsv2.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: things
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-port: "8080"
        dapr.io/app-id: {{ .Values.opentwinsv2.things.dapr.appId | default (printf "%s-things-service" (include "opentwinsv2.fullname" .)) | quote }}
        dapr.io/config: {{ .Values.opentwinsv2.things.dapr.config | default (printf "%s-dapr-config" (include "opentwinsv2.fullname" .)) | quote }}
      labels:
        {{- include "opentwinsv2.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: things
    spec:
      containers:
        - name: opentwinsv2-things
          image: "{{ .Values.opentwinsv2.things.image.repository }}:{{ .Values.opentwinsv2.things.image.tag }}"
          imagePullPolicy: {{ .Values.opentwinsv2.things.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.opentwinsv2.things.service.targetPort | default 8080 }}
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.opentwinsv2.things.service.targetPort | default 8080 }}"
            - name: PostgreSQL__connectionString
              valueFrom:
                secretKeyRef:
                  name: {{ include "opentwinsv2.fullname" . }}-postgresql-connection-string
                  key: postgresql-connection-string
            - name: Dapr__Twins
              value: {{ .Values.opentwinsv2.twins.dapr.appId | default (printf "%s-twins-service" (include "opentwinsv2.fullname" .)) | quote }}
            - name: Dapr__Events
              value: {{ .Values.opentwinsv2.events.dapr.appId | default (printf "%s-events-service" (include "opentwinsv2.fullname" .)) | quote }}
            - name: Dapr__PubSub__Name
              value: {{ include "opentwinsv2.fullname" . }}-kafka-pubsub
            - name: Dapr__StateStore__Name
              value: {{ include "opentwinsv2.fullname" . }}-redis-statestore
            {{- if .Values.opentwinsv2.things.extraEnv }}
            {{- toYaml .Values.opentwinsv2.things.extraEnv | nindent 12 }}
            {{- end }}