apiVersion: v1
kind: PersistentVolume
metadata:
  name: ot-pv-influxdb
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /ot-platform/influxdb