apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      targetPort : {{ .Values.service.targetPort}}
  externalIPs: 
    - 192.168.44.11
  selector:
    name: pod-{{ include "installation.name" . }}-mongodb
