{{- if and .Values.influxdb2.enabled .Values.persistentVolumes.influxdb2 }}

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

{{- end }}