---
apiVersion: v1
kind: Secret
metadata:
  name: permissions
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "ot.name" . }}
    helm.sh/chart: {{ template "ot.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  permissions.json: |
    {{- tpl (.Files.Get "example-permissions.json") . | nindent 4 }}