apiVersion: v1
kind: PersistentVolume
metadata:
  name: ot-pv-grafana
spec:
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /ot-platform/grafana
    type: DirectoryOrCreate
