apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentwinsv2.fullname" . }}-opentwinsv2-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentwinsv2.labels" . | nindent 4 }}