{{- if .Values.ditto.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "ditto-default-data" | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "opentwins.name" . }}
    helm.sh/chart: {{ template "opentwins.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  setup.sh: |
    {{- tpl (.Files.Get "post-install/ditto-default/setup.sh") . | nindent 4 }}
  basic-policy.json: |
    {{- tpl (.Files.Get "post-install/ditto-default/basic-policy.json") . | nindent 4 }}
  ditto-connection.sh: |
    {{- tpl (.Files.Get "post-install/ditto-connection/ditto-connection.sh") . | nindent 4 }}

{{- end }}