{{- if and .Values.example.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "example-raspberry-data" | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "opentwins.name" . }}
    helm.sh/chart: {{ template "opentwins.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  ditto-connection.sh: |
    {{- tpl (.Files.Get "post-install/ditto-connection/ditto-connection.sh") . | nindent 4 }}
  connection.json: |
    {{- tpl (.Files.Get "post-install/example-raspberry/connection.json") . | nindent 4 }}
  setup.sh: |
    {{- tpl (.Files.Get "post-install/example-raspberry/setup.sh") . | nindent 4 }}
  policy.json: |
    {{- tpl (.Files.Get "post-install/example-raspberry/policy.json") . | nindent 4 }}
  type_DHT22.json: |
    {{- tpl (.Files.Get "post-install/example-raspberry/type_DHT22.json") . | nindent 4 }}
  type_raspberry.json: |
    {{- tpl (.Files.Get "post-install/example-raspberry/type_raspberry.json") . | nindent 4 }}

{{- end }} 