{{- if and .Values.hono.enabled .Values.ditto.enabled .Values.connections.ditto.source.hono.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "hono-connection-data" | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "opentwins.name" . }}
    helm.sh/chart: {{ template "opentwins.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  hono-source-connection.sh: |
    {{- tpl (.Files.Get "post-install/ditto-hono-connection/hono-source-connection.sh") . | nindent 4 }}
  {{- if ( has "amqp" .Values.hono.messagingNetworkTypes ) }}
  hono-amqp-source-connection.json: |
    {{- tpl (.Files.Get "post-install/ditto-hono-connection/hono-amqp-source-connection.json") . | nindent 4 }}
  {{- end }}
  {{- if ( has "kafka" .Values.hono.messagingNetworkTypes ) }}
  hono-kafka-source-connection.json: |
    {{- tpl (.Files.Get "post-install/ditto-hono-connection/hono-kafka-source-connection.json") . | nindent 4 }}
  {{- end }}
  
{{- end }}