{{- if and .Values.ditto.enabled .Values.mongodb.enabled}}
{{- $mongoName := include "opentwins.mongodb.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: ditto-mongodb-connection-secret
  labels:
    app.kubernetes.io/name: {{ template "opentwins.name" . }}
    helm.sh/chart: {{ template "opentwins.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  connectivity-uri: {{ .Values.ditto.dbconfig.connectivity.uri | replace "#{PLACEHOLDER_MONGODB_HOSTNAME}#" $mongoName | b64enc | quote }}
  things-uri: {{ .Values.ditto.dbconfig.things.uri | replace "#{PLACEHOLDER_MONGODB_HOSTNAME}#" $mongoName | b64enc | quote }}
  thingsSearch-uri: {{ .Values.ditto.dbconfig.thingsSearch.uri | replace "#{PLACEHOLDER_MONGODB_HOSTNAME}#" $mongoName | b64enc | quote }}
  policies-uri: {{ .Values.ditto.dbconfig.policies.uri | replace "#{PLACEHOLDER_MONGODB_HOSTNAME}#" $mongoName | b64enc | quote }}

{{- end }}
