{{- if and .Values.mosquitto.enabled .Values.ditto.enabled }}
{{- if or .Values.connections.ditto.source.mosquitto.enabled .Values.connections.ditto.target.mosquitto.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "mosquitto-connection-data" | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "opentwins.name" . }}
    helm.sh/chart: {{ template "opentwins.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  ditto-connection.sh: |
    {{- tpl (.Files.Get "post-install/ditto-connection/ditto-connection.sh") . | nindent 4 }}
  mosquitto-source-connection.sh: |
    {{- tpl (.Files.Get "post-install/ditto-mosquitto-connection/mosquitto-source-connection.sh") . | nindent 4 }}
  mosquitto-source-connection.json: |
    {{- tpl (.Files.Get "post-install/ditto-mosquitto-connection/mosquitto-source-connection.json") . | nindent 4 }}
  mosquitto-target-connection.sh: |
    {{- tpl (.Files.Get "post-install/ditto-mosquitto-connection/mosquitto-target-connection.sh") . | nindent 4 }}
  mosquitto-target-connection.json: |
    {{- tpl (.Files.Get "post-install/ditto-mosquitto-connection/mosquitto-target-connection.json") . | nindent 4 }}

{{- end }}  
{{- end }}