apiVersion: v1
version: 0.4.1
appVersion: 0.4.0
name: OpenTwins-Lightweight
description:
  Esta es una plataforma de codigo abierto orientada a gemelos digitales.
keywords:
  - iot-package
  - IoT
  - messaging
  - digital twin
sources:
  - https://github.com/ertis-research/Helm-charts
maintainers:
  - name: sergioip
    email: sergioip@uma.es
