# OpenTwins specific values
##################################################################


# Enabling these persistent volumes or not will depend on how your Kubernetes cluster works. 
# In our case, the cluster creates them automatically, so we don't need to activate them. 
# In other clusters we have seen that they are not created automatically, so to enable persistence it will be necessary to activate them.
persistentVolumes:
  grafana: false
  hono: false
  influxdb2: false


# Automatic connections
connections:
  ditto:
    source:
      hono:
        enabled: true
        tenantName: ditto
        username: "ditto"
        password: "ditto"
      mosquitto:
        enabled: true
        address: "telemetry/#"
    target:
      mosquitto:
        enabled: true
        address: "opentwins/#"
      kafka:
        enabled: false
        topic: "opentwins"
  
  # The data received in Eclipse Ditto must be written to a messaging broker that acts as an intermediary with telegraf, the database collector. 
  # This broker can be Kafka (kafka) or Mosquitto (mqtt). 
  telegraf:
    source:
      mosquitto:
        enabled: true
    target:
      influxdb2:
        enabled: true



# OpenTwins recommended values for Eclipse Ditto
##################################################################
ditto:
  enabled: true # Value added by OpenTwins to indicate if this component should be installed or not
  nameOverride: ditto
  global:
    hashedBasicAuthUsers: false
    basicAuthUsers:
      ditto:
        user: ditto
        password: ditto
      devops:
        user: devops
        password: foobar
  nginx:
    service:
      type: NodePort
      nodePort: 30525
  swaggerui:
    enabled: false
  dittoui:
    enabled: false

  # ----------------------------------------------
  # Do not modify this unless you want to use your own mongodb or ditto mongodb. 
  # Opentwins can display two different mongodb charts. In case of displaying both, the bitnami one will take precedence.
  mongodb:
    enabled: false
  dbconfig:
    uriSecret: ditto-mongodb-connection-secret
  # ----------------------------------------------

  gateway:
    config:
      authentication:
        enablePreAuthentication: true
        devops:
          devopsPassword: foobar
          statusPassword: foobar
  #connectivity:
  #  readinessProbe:
  #    initialDelaySeconds: 30
  #  livenessProbe:
  #    initialDelaySeconds: 80



# OpenTwins recommended values for Mosquitto
##################################################################
mosquitto:
  enabled: false # Value added by OpenTwins to indicate if this component should be installed or not
  nameOverride: mosquitto



# OpenTwins recommended values for Kafka
##################################################################
kafka:
  enabled: true
  


# OpenTwins recommended values for Telegraf
##################################################################
telegraf:
  enabled: true # Value added by OpenTwins to indicate if this component should be installed or not
  config:

# Do no modify
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    processors: [] 
    outputs: [] 
    inputs: [] 
  service:
    enabled: false 
  volumes:
    - name: my-config
      configMap:
        name: opentwins-telegraf-real-config
  volumeMounts:
    - name: my-config
      mountPath: /additional_config
  args:
    - "--config=/etc/telegraf/telegraf.conf"
    - "--config-directory=/additional_config"
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


# OpenTwins recommended values for InfluxDB2
##################################################################
influxdb2:
  enabled: true # Value added by OpenTwins to indicate if this component should be installed or not
  nameOverride: influxdb2
  persistence:
    enabled: true
  service:
    type: NodePort
  image:
    pullPolicy: Always
  adminUser:
    organization: "opentwins"
    bucket: "default"
    password: "password"
# ----------------------------------------------
# We have generated this token randomly in this page: https://generate-random.org/api-token-generator
# We recommend to generate one of your own and assign it to this value in your values file.
    token: "Hjh3ysMQ6evK=qqpFSYqn-s3JGovJLfHxyCDM=eNNZkdM-uuro93dNtJcodejLYYob2geKQ/29z3Kxui=y6FlL?dZeU9EFRxrYn284V/kZG5==jxLVAMJrYOv?LF79ahwIbhvstMN6gmfQ3DH7/IzUB7VlBZK-cd8aN7YqiFrYRLkBUv7H0QkbqPxgf2dMgCMCwZaLMk9RUeMaBfx2lQ=Mq1EEJJw-Jp!BmpCDnhlc!6D22PaE=Y3sgWWNhRv8oP"
# ----------------------------------------------



# OpenTwins recommended values for Grafana
##################################################################
grafana:
  enabled: true # Value added by OpenTwins to indicate if this component should be installed or not
  persistence:
    enabled: true
  service:
    type: NodePort
    nodePort: 45718
  adminUser: admin
  adminPassword: admin
  sidecar:
    datasources:
      enabled: true



# OpenTwins recommended values for Eclipse Hono
##################################################################
hono:
  enabled: false # Value added by OpenTwins to indicate if this component should be installed or not
  nameOverride: hono
  prometheus:
    createInstance: false
  grafana:
    enabled: false
  useLoadBalancer: false
  probes:
    livenessProbe:
      initialDelaySeconds: 900
    readinessProbe:
      initialDelaySeconds: 45
  messagingNetworkTypes:
  - "amqp"
  kafka:
    auth:
      sasl:
        jaas:
          clientUsers:
            - "hono"
            - "ditto"
          clientPasswords:
            - "hono-secret"
            - "ditto"
  kafkaMessagingClusterExample:
    enabled: false
  amqpMessagingNetworkExample:
    enabled: true
  deviceRegistryExample:
    type: mongodb
    addExampleData: false
    mongoDBBasedDeviceRegistry:
      mongodb:
        host: '{{ .Release.Name }}-mongodb' # The values are processed via the 'tpl' function here in Eclipse Hono helm, allowing the inclusion of the release name
        port: 27017
        dbName: hono
    hono:
      registry:
          http:
            insecurePortEnabled: true
  adapters: # This needs to be defined for the Eclipse Hono Helm to work (it seems to be a bug)
    mqtt:
      hono:
        mqtt:
          insecurePortEnabled: true
    http:
      hono:
        http:
          insecurePortEnabled: true
    amqp:
      hono:
        amqp:
          insecurePortEnabled: true



# OpenTwins recommended values for bitnami MongoDB
##################################################################
mongodb:
  enabled: true
  nameOverride: mongodb
  service:
    type: NodePort
    nodePorts:
      mongodb: 30717
  persistence:
    enabled: true
  volumePermissions:
    enabled: true
  auth:
    enabled: false



# OpenTwins recommended values for ertis MongoDB 
##################################################################
OpenTwins-MongoDB:
  enabled: false # Value added by OpenTwins to indicate if this component should be installed or not
  nameOverride: mongodb
  auth:
    enabled: false
  securityContext:
    enabled: false
  persistence:
    enabled: false
  metadata:
    labels:
      app: database
      selector: mongodb
  service:
    type: NodePort
    nodePort: 30718
  spec:
    containers:
    - name: mongodb
      image:
        repository: mongo
        tag: 4.4.6
      # env:
      #   - name: MONGO_INITDB_ROOT_USERNAME
      #     value: admin
      #   - name: MONGO_INITDB_ROOT_PASSWORD
      #     value: password