apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-ditto-hono-connection"
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: "post-install"
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['NS = {{ .Release.Namespace }}', 'NS = {{ .Release.Name }}', 'HONO_TENANT = ditto', 'DITTO_DEVOPS_PWD=$(kubectl --namespace ${NS} get secret ${RELEASE}-ditto-gateway-secret -o jsonpath="{.data.devops-password}" | base64 --decode)']
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1