{{- if and .Values.example.enabled }}

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-example-raspberry"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # Esto es lo que define este recurso como un gancho. Sin esta línea, 
    # el trabajo se considera parte del release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-post-install-example-raspberry"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: "post-install-example-raspberry"
        image: "curlimages/curl:8.2.1"
        env:
          - name: DITTO_HOST
            value: {{ include "opentwins.ditto.fullname" . | quote }}
          - name: DITTO_NGINX_PORT
            value: {{ .Values.ditto.nginx.service.port | quote }}
          - name: EXTENDED_API_HOST
            value: {{ include "opentwins.extendedAPI.fullname" . | quote }}
          - name: EXTENDED_API_PORT
            value: {{ .Values.extendedAPI.service.port | quote }}
          - name: DEVOPS_USER
            value: {{ .Values.ditto.global.basicAuthUsers.devops.user | quote }}
          - name: DEVOPS_PASSWORD
            value: {{ .Values.ditto.global.basicAuthUsers.devops.password | quote }}
          - name: DITTO_USER
            value: {{ .Values.ditto.global.basicAuthUsers.ditto.user | quote }}
          - name: DITTO_PASSWORD
            value: {{ .Values.ditto.global.basicAuthUsers.ditto.password | quote }}
        command:
        - /bin/sh
        - -c
        - |
          cp /var/run/opentwins/example-raspberry-data/* /tmp/
          chmod +x /tmp/setup.sh
          cd /tmp
          ./setup.sh
        volumeMounts:
        - name: example-raspberry-data
          mountPath: "/var/run/opentwins/example-raspberry-data"
          readOnly: true
        - name: ditto-gw-users
          mountPath: "/var/run/opentwins/ditto-gw-users"
          readOnly: true
      volumes:
      - name: example-raspberry-data
        secret:
          secretName: {{ printf "%s-%s" .Release.Name "example-raspberry-data" }}
          defaultMode: 0555
      - name: ditto-gw-users
        secret:
          secretName: {{ printf "%s-%s" ( include "opentwins.ditto.fullname" . ) "gateway-secret" }}

{{- end }}