apiVersion: v1
kind: PersistentVolume
metadata:
  name: dt-pv-mongodb
spec:
  accessModes:
   - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /mnt/dt-platform/mongodb
    type: DirectoryOrCreate
  claimRef:
    namespace: digitaltwins
    name: dt-pvc-mongodb
