name: Release Charts

on:
  push:
    branches:
      - main

env:
  CHARTS_DIR: "."
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add repositories
        run: |
          for dir in $(ls -d ${{ env.CHARTS_DIR }}/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | grep -E 'https?://' | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: "${{ env.CHARTS_DIR }}"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
